-- ============================================
-- FINTECH DATABASE CREATION SCRIPT FOR ORACLE
-- ============================================

-- Create Sequences
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RECEITA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DESPESA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DIVIDA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INVESTIMENTO START WITH 1 INCREMENT BY 1 NOCACHE;

-- Create USUARIO Table
CREATE TABLE TB_USUARIO (
    ID_USUARIO          NUMBER PRIMARY KEY,
    NM_USUARIO          VARCHAR2(100) NOT NULL,
    DS_EMAIL            VARCHAR2(100) NOT NULL UNIQUE,
    DS_SENHA            VARCHAR2(255) NOT NULL,
    DT_CRIACAO          TIMESTAMP DEFAULT SYSDATE NOT NULL,
    DT_ATUALIZACAO      TIMESTAMP DEFAULT SYSDATE NOT NULL
);

CREATE INDEX IDX_USUARIO_EMAIL ON TB_USUARIO(DS_EMAIL);

-- Create RECEITA Table
CREATE TABLE TB_RECEITA (
    ID_RECEITA          NUMBER PRIMARY KEY,
    ID_USUARIO          NUMBER NOT NULL,
    DS_RECEITA          VARCHAR2(255) NOT NULL,
    DS_FONTE            VARCHAR2(100) NOT NULL,
    VL_RECEITA          NUMBER(12,2) NOT NULL,
    DT_RECEITA          DATE NOT NULL,
    DT_CRIACAO          TIMESTAMP DEFAULT SYSDATE NOT NULL,
    DT_ATUALIZACAO      TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_RECEITA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE INDEX IDX_RECEITA_USUARIO ON TB_RECEITA(ID_USUARIO);
CREATE INDEX IDX_RECEITA_DATA ON TB_RECEITA(DT_RECEITA);

-- Create DESPESA Table
CREATE TABLE TB_DESPESA (
    ID_DESPESA          NUMBER PRIMARY KEY,
    ID_USUARIO          NUMBER NOT NULL,
    NM_DESPESA          VARCHAR2(255) NOT NULL,
    DS_CATEGORIA        VARCHAR2(100) NOT NULL,
    VL_DESPESA          NUMBER(12,2) NOT NULL,
    DT_DESPESA          DATE NOT NULL,
    DT_CRIACAO          TIMESTAMP DEFAULT SYSDATE NOT NULL,
    DT_ATUALIZACAO      TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_DESPESA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE INDEX IDX_DESPESA_USUARIO ON TB_DESPESA(ID_USUARIO);
CREATE INDEX IDX_DESPESA_CATEGORIA ON TB_DESPESA(DS_CATEGORIA);
CREATE INDEX IDX_DESPESA_DATA ON TB_DESPESA(DT_DESPESA);

-- Create DIVIDA Table
CREATE TABLE TB_DIVIDA (
    ID_DIVIDA           NUMBER PRIMARY KEY,
    ID_USUARIO          NUMBER NOT NULL,
    DS_CREDOR           VARCHAR2(255) NOT NULL,
    DS_DESCRICAO        VARCHAR2(255) NOT NULL,
    VL_DIVIDA           NUMBER(12,2) NOT NULL,
    DT_VENCIMENTO       DATE NOT NULL,
    ST_DIVIDA           VARCHAR2(20) DEFAULT 'ativa' NOT NULL,
    DT_CRIACAO          TIMESTAMP DEFAULT SYSDATE NOT NULL,
    DT_ATUALIZACAO      TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_DIVIDA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE INDEX IDX_DIVIDA_USUARIO ON TB_DIVIDA(ID_USUARIO);
CREATE INDEX IDX_DIVIDA_STATUS ON TB_DIVIDA(ST_DIVIDA);
CREATE INDEX IDX_DIVIDA_VENCIMENTO ON TB_DIVIDA(DT_VENCIMENTO);

-- Create INVESTIMENTO Table
CREATE TABLE TB_INVESTIMENTO (
    ID_INVESTIMENTO     NUMBER PRIMARY KEY,
    ID_USUARIO          NUMBER NOT NULL,
    NM_INVESTIMENTO     VARCHAR2(255) NOT NULL,
    DS_TIPO             VARCHAR2(100) NOT NULL,
    VL_INVESTIDO        NUMBER(12,2) NOT NULL,
    VL_ATUAL            NUMBER(12,2) NOT NULL,
    TX_RENTABILIDADE    NUMBER(10,2),
    DT_CRIACAO          TIMESTAMP DEFAULT SYSDATE NOT NULL,
    DT_ATUALIZACAO      TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_INVESTIMENTO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE INDEX IDX_INVESTIMENTO_USUARIO ON TB_INVESTIMENTO(ID_USUARIO);
CREATE INDEX IDX_INVESTIMENTO_TIPO ON TB_INVESTIMENTO(DS_TIPO);

-- Commit all changes
COMMIT;

-- Display confirmation
SELECT 'Fintech Database created successfully!' AS STATUS FROM DUAL;
